amuletspade231/CodeU-Spring-2019

- src/main/java/com/google/codeu/servlets/StatsPageServlet.java
Added a new (mostly empty) servlet for the stats page, so that navigating to it displays a Hello World page. 
Recommended to PR at this stage by the project instructions.
> Created skeleton servlet for the stats page

- src/main/java/com/google/codeu/servlets/AboutMeServlet.java
Completed part 2 of about me feature. Servlet just prints out "Hello World".
> Made a servlet for the AboutMe page

- src/main/java/com/google/codeu/data/Datastore.java
Previous PR for `Datastore.java` was missing a key import statement -- I've now added it and verified that local servers successfully start.
> Added missing import statement for FetchOptions

- src/main/java/com/google/codeu/data/Datastore.java
- src/main/java/com/google/codeu/servlets/MessageFeedServlet.java
loadMessages() will take in a PreparedQuery and load in all the messages into a list that will be returned to getMessages(). I have also added another getMessages() function that will get the messages from all users.
> Created a helper function for getMessages() called loadMessages().

- src/main/java/com/google/codeu/data/Datastore.java
- src/main/java/com/google/codeu/servlets/MessageFeedServlet.java
Also fixed exception handling in loadMessages() for Datastore.java
> Added servlet logic to get message data.

- src/main/java/com/google/codeu/servlets/MessageFeedServlet.java
- src/main/webapp/feed.html
- src/main/webapp/js/feed-loader.js
- src/main/webapp/js/navigation-loader.js
Created: 
- feed.html
- feed-loader.js
Added public feed link to navigation-loader.js
> Created public feed web page.

- src/main/webapp/js/user-page-loader.js
- src/main/webapp/user-page.html
Added some code to output a textbox for the about me page.
> User Page modification - added about me textbox

- src/main/java/com/google/codeu/data/Datastore.java
- src/main/java/com/google/codeu/data/User.java
- src/main/java/com/google/codeu/servlets/AboutMeServlet.java
- src/main/java/com/google/codeu/servlets/MessageServlet.java
Created a User class; added more to datastore.java; cleaning user data
> added code parts4-6

- src/main/java/com/google/codeu/servlets/MessageServlet.java
Removed a Jsoup line parsing the about-me parameter from the request.
> Removed AboutMeServlet line from MessageServlet

- .gitignore
- pom.xml
- src/main/java/com/google/codeu/data/Datastore.java
- src/main/java/com/google/codeu/data/Message.java
- src/main/java/com/google/codeu/servlets/MessageServlet.java
- src/main/webapp/js/user-page-loader.js
Connected Google's NLP API to analyze the positive/negative sentiment score of individual messages. Added the score of messages to their headers, scores range from -1.0 to 1.0.
Updated maven dependencies to include `netty-tcnative`.
Added `credentials.json` file, and added that file to the `.gitignore` so that private keys don't get committed and pushed.
> Sentiment Analysis MVP

- src/main/java/com/google/codeu/servlets/HomeServlet.java
- src/main/webapp/WEB-INF/home.jsp
- src/main/webapp/feed.html
- src/main/webapp/index.html
- src/main/webapp/user-page.html
We now have a new link called "/home" that loads the home page along with the full navigation bar faster.
Even though the content is the same, it is different than the default home link which is mapped to "/"
However, if you click on the "Home" hyperlink, you will be sent to "/home"
> Implemented server-side rendering for the home page's navigation bar.

- src/main/java/com/google/codeu/servlets/HomeServlet.java
- src/main/webapp/WEB-INF/jsp/home.jsp
- src/main/webapp/WEB-INF/jspf/navigation.jspf
We can now add the server-rendered navigation bar to other web pages without redundant code.
> Added navigation bar as a jspf.

- src/main/java/com/google/codeu/data/Datastore.java
- src/main/java/com/google/codeu/servlets/ChartServlet.java
- src/main/webapp/chart.html
- src/main/webapp/js/chart-loader.js
Created HTML and JS files for displaying charts.
Currently displays a curved line chart for average sentiment over time, based on temporary hard-coded data.
> Charts Part 1 (Hard-Coded Data)

- src/main/java/com/google/codeu/data/Datastore.java
- src/main/java/com/google/codeu/servlets/ChartServlet.java
- src/main/webapp/WEB-INF/jsp/chart.jsp
- src/main/webapp/js/chart-loader.js
- /charts now uses JSP instead of chart.html
- now gets JSON from /feed-json instead of both of them duplicating the operation
- added navigation header for charts
- refactored Datastore.getAllMessages() to remove duplicated code
> Charts using JSP and pulling JSON from /feed-json

- src/main/java/com/google/codeu/data/Datastore.java
- src/main/java/com/google/codeu/data/User.java
- src/main/java/com/google/codeu/servlets/AboutMeServlet.java
- src/main/webapp/WEB-INF/jsp/user-page.jsp
- src/main/webapp/css/user-page.css
- src/main/webapp/js/user-page-loader.js
- Added a frontend commission slider that is only visible on your own page
- Added `User.isTakingCommissions` attribute and handling for it
> Added commission toggle

- src/main/java/com/google/codeu/data/Datastore.java
- src/main/java/com/google/codeu/data/Message.java
- src/main/java/com/google/codeu/servlets/MessageServlet.java
- src/main/webapp/WEB-INF/index.yaml
- src/main/webapp/js/user-page-loader.js
If you're running this on the dev server, old messages will not show up on the user pages since the messages are filtered by "recipient," which is a parameter that old messages do not have.
> Implemented direct messages.

- src/main/java/com/google/codeu/servlets/MessageServlet.java
Fixing a missing bracket in MessageServlet.java
> Minor syntax fix + removed print statement and added comment

- src/main/webapp/WEB-INF/jsp/user-page.jsp
- src/main/webapp/css/user-page.css
- src/main/webapp/js/user-page-loader.js
You can now toggle between viewing all of a user's posts and only viewing their posts that contain images and videos, by clicking the "Gallery" button at the top of their post column.
> Gallery Display Toggle

- src/main/webapp/WEB-INF/jsp/feed.jsp
- src/main/webapp/WEB-INF/jsp/index.jsp
- src/main/webapp/WEB-INF/jspf/navigation.jspf
- src/main/webapp/css/feedcss.css
- src/main/webapp/css/indexcss.css
- src/main/webapp/css/main.css
I changed the look of the home page and the feed page. Let me know of your thoughts about the pages. Still working on user page
> Changed the Outlook of the HomePage and Feed page 

- src/main/webapp/WEB-INF/jsp/chart.jsp
- src/main/webapp/WEB-INF/jsp/feed.jsp
- src/main/webapp/WEB-INF/jsp/index.jsp
- src/main/webapp/WEB-INF/jsp/stats.jsp
- src/main/webapp/WEB-INF/jsp/user-page.jsp
- src/main/webapp/WEB-INF/jspf/navigation.jspf
- src/main/webapp/css/feedcss.css
- src/main/webapp/css/indexcss.css
- src/main/webapp/css/main.css
- src/main/webapp/css/user-page.css
- src/main/webapp/js/feed-loader.js
- src/main/webapp/js/user-page-loader.js
Edited the User Page and added headers to Stats and Chart pages. 
User page is still in progress. Figuring out how to upload a profile pic and editing how the About me text box returns texts(not return all in one line).
> Edited User Page

- src/main/java/com/google/codeu/data/Datastore.java
- src/main/java/com/google/codeu/servlets/MessageServlet.java
- src/main/webapp/WEB-INF/jsp/user-page.jsp
- src/main/webapp/js/feed-loader.js
- src/main/webapp/js/user-page-loader.js
Changed reply buttons to say "Comment" to match placeholder text.
Changed message button to say "Post."
Added indent margins to replies.
> Minor appearance changes to messages and replies.

- src/main/java/com/google/codeu/data/Datastore.java
- src/main/java/com/google/codeu/servlets/AboutMeServlet.java
- src/main/webapp/WEB-INF/jsp/index.jsp
- src/main/webapp/WEB-INF/jsp/user-page.jsp
- src/main/webapp/WEB-INF/jspf/navigation.jspf
- src/main/webapp/css/indexcss.css
- src/main/webapp/css/main.css
- src/main/webapp/css/user-page.css
- src/main/webapp/js/user-page-loader.js
1. - HomePage
Changed the font size of navigation
Added a tiny blurb of what should do. Description of website will be placed in the discription box in showcase website.
Userpage
able to post multiple lines in about me.
> Updated home page and userpage

- src/main/webapp/WEB-INF/jsp/user-page.jsp
- src/main/webapp/js/feed-loader.js
- src/main/webapp/js/user-page-loader.js
Added a button that shows/hides the replies of a message.
May need refactoring.
> Implemented collapsible replies.

- src/main/java/com/google/codeu/data/Datastore.java
- src/main/webapp/WEB-INF/jsp/user-page.jsp
- Gallery/All buttons are now more clearly labeled.
- The `Datastore.getGallery` method now filters out images not posted by the user whose page you're viewing.
> Gallery display fixes

- src/main/webapp/WEB-INF/jsp/user-page.jsp
- src/main/webapp/js/user-page-loader.js
The gallery mode now displays a message if the user's commissions are on. 
The message appears/disappears even when the user is actively toggling their status.
> Gallery commissions message
